
from lib.exception.NestedException import *


class OOException(NestedException):
	pass